---- ---- ---- ---- xxx_STD_AP_IvoiiImport_iFace
Create Table xxx_STD_AP_IvoiiImport_iFace
(
  ORG_ID              NUMBER(15) NOT NULL,
  BATCH_ID            NUMBER(15),
  BATCH_NUMBER        VARCHAR2(50),
  COM_CODE            VARCHAR2(25) NOT NULL,
  PERIOD_NAME         VARCHAR2(15) NOT NULL,
  INVOII_TII VARCHAR2(18) NOT NULL,
  INVOICE_NUM         VARCHAR2(50),
  INVOII_CURR         VARCHAR2(15) NOT NULL,
  INVOIIHEADER_AMOUNT NUMBER NOT NULL,
  INVOIIITAX_AMOUNT   NUMBER NOT NULL,
  INVOII_DATE         DATE NOT NULL,
  INVOII_GL_DATE      DATE NOT NULL,
  SUPP_NAME           VARCHAR2(240) NOT NULL,
  SUPP_NUMBER         VARCHAR2(30) NOT NULL,
  SUPP_SITECODE       VARCHAR2(15) NOT NULL,
  WITHHOLD_TAXCODE    VARCHAR2(25),
  TAXVAT_CODE         VARCHAR2(50),
  TAXVAT_RATE NUMBER,
  PMTS_TERMS          VARCHAR2(30) NOT NULL,
  PMTS_METHOD         VARCHAR2(25) NOT NULL,
  PMTS_GROUP          VARCHAR2(25),
  L_INVOIILINE_NUMBER NUMBER NOT NULL,
  INVOIILINE_GL_DATE  DATE NOT NULL,
  GL_COA_CODE         VARCHAR2(233),
  SEGMENT1            VARCHAR2(25),
  SEGMENT2            VARCHAR2(25),
  SEGMENT3            VARCHAR2(25),
  SEGMENT4            VARCHAR2(25),
  SEGMENT5            VARCHAR2(25),
  SEGMENT6            VARCHAR2(25),
  SEGMENT7            VARCHAR2(25),
  SEGMENT8            VARCHAR2(25),
  SEGMENT9            VARCHAR2(25),
  L_INVOIILINE_AMOUNT NUMBER NOT NULL,
  L_INVOIILINETAX_AMOUNT NUMBER NOT NULL,
  IMPORTED_FLAG       VARCHAR2(1) NOT NULL
)
tablespace APPS_TS_TX_DATA
  pctfree 10
  initrans 1
  maxtrans 255;

---- ---- ---- ---- xxx_STD_AP_IvoiiImport_Headers
Create Table xxx_STD_AP_IvoiiImport_Headers
(
  ORG_ID              NUMBER(15) NOT NULL,
  BATCH_ID            NUMBER(15) NOT NULL,
  BATCH_NUMBER        VARCHAR2(50) NOT NULL,
  COM_CODE            VARCHAR2(25) NOT NULL,
  PERIOD_NAME         VARCHAR2(15) NOT NULL,
  INVOII_TII VARCHAR2(18) NOT NULL,
  INVOII_IFACEID      NUMBER(15) NOT NULL,
  INVOICE_NUM         VARCHAR2(50) NOT NULL,
  INVOICE_XNUM         VARCHAR2(50),
  INVOII_CURR         VARCHAR2(15) NOT NULL,
  INVOIIHEADER_AMOUNT NUMBER NOT NULL,
  INVOIIITAX_AMOUNT   NUMBER NOT NULL,
  INVOII_DATE         DATE NOT NULL,
  INVOII_GL_DATE      DATE NOT NULL,
  SUPP_NAME           VARCHAR2(240) NOT NULL,
  SUPP_NUMBER         VARCHAR2(30) NOT NULL,
  SUPP_SITECODE       VARCHAR2(15) NOT NULL,
  SUPP_ID             NUMBER(15) NOT NULL,
  SUPP_SITEID         NUMBER(15) NOT NULL,
  WITHHOLD_TAXCODE    VARCHAR2(25),
  WITHHOLD_TAXID      NUMBER(15),
  --TAXVAT_CODE         VARCHAR2(50),
  --TAXVAT_RATE NUMBER,
  PMTS_TERMS          VARCHAR2(30) NOT NULL,
  PMTSTERMS_ID NUMBER NOT NULL,
  PMTS_METHOD         VARCHAR2(25) NOT NULL,
  PMTS_GROUP          VARCHAR2(25) NOT NULL,
  IMPORTED_FLAG       CHAR(1) NOT NULL,
  
  CREATED_BY          NUMBER(15) NOT NULL,
  CREATION_DATE       DATE NOT NULL,
  LAST_UPDATED_BY     NUMBER(15) NOT NULL,
  LAST_UPDATE_DATE    DATE NOT NULL,
  LAST_UPDATE_LOGIN   NUMBER(15) NOT NULL
)
tablespace APPS_TS_TX_DATA
  pctfree 10
  initrans 1
  maxtrans 255;


---- ---- ---- ---- xxx_STD_AP_IvoiiImport_Lines
Create Table xxx_STD_AP_IvoiiImport_Lines
(
  ORG_ID              NUMBER(15) NOT NULL,
  BATCH_ID            NUMBER(15) NOT NULL,
  BATCH_NUMBER        VARCHAR2(50) NOT NULL,
  COM_CODE            VARCHAR2(25) NOT NULL,
  PERIOD_NAME         VARCHAR2(15) NOT NULL,
  INVOII_TII VARCHAR2(18) NOT NULL,
  INVOII_LINETII VARCHAR2(18) NOT NULL,
  INVOICE_NUM         VARCHAR2(50) NOT NULL,
  INVOII_IFACEID      NUMBER(15) NOT NULL,
  INVOII_IFACELINEID  NUMBER(15) NOT NULL,
  INVOII_CURR         VARCHAR2(15) NOT NULL,
  INVOIIHEADER_AMOUNT NUMBER NOT NULL,
  INVOIIITAX_AMOUNT   NUMBER NOT NULL,
  INVOIILINE_GL_DATE  DATE NOT NULL,
  WITHHOLD_TAXCODE    VARCHAR2(25),
  WITHHOLD_TAXID      NUMBER(15),
  TAXVAT_CODE         VARCHAR2(50),
  LINE_GROUPNUM NUMBER,
  TAXVAT_RATE NUMBER,
  L_INVOIILINE_NUMBER NUMBER,
  GL_COA_CODE         VARCHAR2(233),
  GL_CCID NUMBER,
  SEGMENT1            VARCHAR2(25),
  SEGMENT2            VARCHAR2(25),
  SEGMENT3            VARCHAR2(25),
  SEGMENT4            VARCHAR2(25),
  SEGMENT5            VARCHAR2(25),
  SEGMENT6            VARCHAR2(25),
  SEGMENT7            VARCHAR2(25),
  SEGMENT8            VARCHAR2(25),
  SEGMENT9            VARCHAR2(25),
  L_INVOIILINE_AMOUNT NUMBER NOT NULL,
  L_INVOIILINETAX_AMOUNT NUMBER NOT NULL,
  IMPORTED_FLAG       VARCHAR2(1) NOT NULL,
  
  CREATED_BY          NUMBER(15) NOT NULL,
  CREATION_DATE       DATE NOT NULL,
  LAST_UPDATED_BY     NUMBER(15) NOT NULL,
  LAST_UPDATE_DATE    DATE NOT NULL,
  LAST_UPDATE_LOGIN   NUMBER(15) NOT NULL
)
tablespace APPS_TS_TX_DATA
  pctfree 10
  initrans 1
  maxtrans 255;
