---- ---- ---- ---- HR_UserInfo_Imported_iFace
Create table HR_UserInfo_Imported_iFace
( No Number not null,
  EMP_LASTNAME   VARCHAR2(150) NOT NULL,
  EMP_FULLNAME   VARCHAR2(240),
  EMP_TII        VARCHAR2(80) NOT NULL,
  SEX_CODE       VARCHAR2(30) NOT NULL,
  IDCARD_CODE    VARCHAR2(30) NOT NULL,
  SUPPER_MANAGER VARCHAR2(150),
  EMP_START_DATE DATE NOT NULL,
  BIRTH_DATE     DATE NOT NULL,
  MARITAL_STATUS VARCHAR2(30) NOT NULL,
  EMAIL_ADDRESS  VARCHAR2(240) NOT NULL,
  HR_ORG         VARCHAR2(240) NOT NULL,
  HR_GROUP       VARCHAR2(240) NOT NULL,
  JOB_NAME       VARCHAR2(700) NOT NULL,
  POSTION_NAME   VARCHAR2(240) NOT NULL,
  SALARY_GRADE   VARCHAR2(240) NOT NULL,
  LOCATION_CODE  VARCHAR2(60) NOT NULL,
  GL_SOB         VARCHAR2(20),
  EXPNC_ACCOUNT  VARCHAR2(233),
  IMPORTED_FLAG  VARCHAR2(2) NOT NULL
)
tablespace APPS_TS_TX_DATA
  pctfree 10
  initrans 1
  maxtrans 255;
